name: Security Scan

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        run: bandit -r .
